"""
Obtain the PQS window BED file from the epiG4NN data repository.

The set of 2,105,836 putative quadruplex sequences (PQS) used in this study
was generated by the epiG4NN authors (Korsak et al. 2023) using a custom
regex-based search of hg19 covering canonical, bulged, and irregular G4 motifs.
We use their pre-computed BED file directly rather than re-running the scan.

Source:  Korsak et al. (2023) epiG4NN data deposit
         Zenodo DOI: 10.5281/zenodo.8144456
         GitHub:     https://github.com/anyakors/epiG4NN

Files downloaded:
  data/PQS_padded.bed   — 2,105,836 sites, each extended to a 1000-bp window
                          centered on the PQS midpoint (BED columns: chrom,
                          start, end, pqs_id, ., strand)

Usage:
  python data_prep/01_scan_pqs.py --out pqs/PQS_padded.bed

Requires: wget or curl on PATH (or download manually from the Zenodo link above).
"""
import argparse
import os
import subprocess
import sys

ZENODO_BASE = "https://zenodo.org/records/8144456/files"
FILENAME    = "PQS_padded.bed"


def download(url, dest):
    os.makedirs(os.path.dirname(os.path.abspath(dest)), exist_ok=True)
    for tool in ("wget", "curl"):
        if subprocess.run(["which", tool], capture_output=True).returncode == 0:
            if tool == "wget":
                cmd = ["wget", "-q", "-O", dest, url]
            else:
                cmd = ["curl", "-fsSL", "-o", dest, url]
            print(f"Downloading {url} → {dest}")
            result = subprocess.run(cmd)
            if result.returncode == 0:
                return
            print(f"  {tool} failed (exit {result.returncode})")
    sys.exit(
        "ERROR: neither wget nor curl found on PATH.\n"
        f"Please download manually:\n  {url}\nand place it at:\n  {dest}"
    )


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default="pqs/PQS_padded.bed",
                   help="Destination path for PQS_padded.bed (default: pqs/PQS_padded.bed)")
    args = p.parse_args()

    url = f"{ZENODO_BASE}/{FILENAME}"
    download(url, args.out)

    with open(args.out) as fh:
        n = sum(1 for _ in fh)
    print(f"Downloaded {n:,} PQS sites → {args.out}")
    if n != 2_105_836:
        print(f"WARNING: expected 2,105,836 lines, got {n:,}. Check the download.")


if __name__ == "__main__":
    main()
